name: Publish new versions

on:
  push:
    branches:
      - master

deploy:
  runs-on: ubuntu-latest
  steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: ./deploy.sh
